---

resources:
  languages:
    description:
      Languages objects represent each available language in
      Transifex.
    operations:
      get_many:
        summary: List languages
        filters:
          code:
            description: The code of the language to get details
          code__any:
            description:
              A list of codes of the languages to get details. This
              will fetch any available.
      get_one:
        summary: Get language
    display: '{{.Attributes.name}} ({{.Attributes.code}})'
  organizations:
    description:
      Represents Transifex's organizations. Every user can be a member of one
      or multiple organizations. Only the organizations the authenticated user
      belongs to will appear here.
    operations:
      get_many:
        summary: List organizations
        filters:
          slug:
            description: Filter results by slug
      get_one:
        summary: Get organization
    display: '{{.Attributes.name}} ({{.Attributes.slug}})'
  projects:
    operations:
      get_many:
        summary: List projects
        filters:
          organization:
            description: Filter results by an organization
            resource: organizations
            required: true
          slug:
            description: Filter results by slug
          name:
            description: Filter results by name
      get_one:
        summary: Get project
      delete:
        summary: Delete project
      create_one:
        summary: Create a Project
        attributes:
          required: [name, slug, private]
          optional: [
            type, tags, description, long_description,
            translation_memory_fillup, machine_translation_fillup,
            homepage_url, instructions_url, repository_url, license
          ]
        relationships:
          required:
            organization: organizations
            source_language: languages
          optional:
            team: teams
      edit_one:
        summary: Update a Project
        fields: [name, tags, description, long_description, private, archived,
                 translation_memory_fillup, machine_translation_fillup,
                 homepage_url, repository_url, instructions_url, license, team]
    relationships:
      team:
        resource: teams
        operations:
          get:
            summary: Get project team
          change:
            summary: Update team relationship
      languages:
        resource: languages
        operations:
          get:
            summary: List project languages
          add:
            summary: Add languages to project
          remove:
            summary: Remove languages from project
          reset:
            summary: Reset project languages
    display: '{{.Attributes.name}} ({{.Attributes.slug}})'
  teams:
    operations:
      get_many:
        summary: List teams
        filters:
          organization:
            description: Filter results by an organization
            resource: organizations
            required: true
          slug:
            description: Filter results by slug
          name:
            description: Filter results by name
      create_one:
        summary: Create a Team
        attributes:
          required: [name]
          optional: [auto_join, cla, cla_required]
        relationships:
          required:
            organization: organizations
    display: '{{.Attributes.Name}} ({{.Attributes.slug}})'
  resources:
    operations:
      get_many:
        summary: List resources
        filters:
          project:
            description: Filter results by a project
            resource: projects
            required: true
          slug:
            description: Filter results by slug
          name:
            description: Filter results by name
      create_one:
        summary: Create a Resource
        attributes:
          required: [slug, name]
          optional: [
            priority, accept_translations, categories, 
            i18n_options, mp4_url, ogg_url, webm_url, youtube_url
          ]
        relationships:
          required:
            project: projects
            i18n_format: i18n_formats
          optional:
            base: resources
    display: '{{.Attributes.name}} ({{.Attributes.slug}})'
  i18n_formats:
    operations:
      get_many:
        summary: List i18n formats
        filters:
          organization:
            description: Filter results by an organization
            resource: organizations
            required: true
          name:
            description: Filter results by name
    display: '{{.Attributes.name}}'
  project_webhooks:
    operations:
      create_one:
        summary: Create a Project Webhook
        attributes:
          required: [event_type, active, callback_url]
          optional: [secret_key]
        relationships:
          required:
            project: projects
    display: '{{.Attributes.name}} ({{.Attributes.slug}})'
