builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: tx
    ldflags:
      - -s -w -X 'github.com/transifex/cli/internal/txlib.Version={{.Version}}'
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "tx-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
